### ISSUE TITLE
Not working for old Linux OS

### ISSUE THREAD

**Issue by c02y** [nelsonenzo/tmux-appimage#1]
~~~
$ ./tmux-debian-6d3d47c2-x86_64.AppImage
./tmux-debian-6d3d47c2-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./tmux-debian-6d3d47c2-x86_64.AppImage)
./tmux-debian-6d3d47c2-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./tmux-debian-6d3d47c2-x86_64.AppImage)
./tmux-debian-6d3d47c2-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by ./tmux-debian-6d3d47c2-x86_64.AppImage)

~~~
for Red Hat Enterprise Linux Server release 7.6 (Maipo)

but works for new Linux like Manjaro (latest update)

I believe appimage file should contains all dependencies.

For example, the appimage of neovim works in Red Hat Enterprise Linux Server release 7.6 (Maipo) too.

**Comment by nelsonenzo** [comment]
Thanks for reporting.  This is my first App Image build, so I may have missed some dependencies.  I'll see if I can fix.

**Comment by nelsonenzo** [comment]
I found this specific issue with AppImages on older distributions https://docs.appimage.org/packaging-guide/other-resources/ingredients.html#binaries-compiled-on-old-enough-base-system

Following the advice there, I changed the docker base to Centos 6.9.  I verified the produced AppImage now works on:
```
Centos 6.9
Centos 7.6
Fedora 31
Debian 7
Ubuntu 18
```
@c02y I'll leave this open for a bit if you could kindly retest the [latest AppImage release](https://github.com/nelsonenzo/tmux-appimage/releases/tag/3.0a-appimage0.1.0), or git pull master and docker build & run.  If you are building the docker container locally, please note the changes in the readme, the docker run step has been simplified.  Thank you!

**Comment by nelsonenzo** [comment]
Just gonna close it unless I hear back from you otherwise.
