### ISSUE TITLE
Appimage for 3.2a?

### ISSUE THREAD

**Issue by jrwrigh** [nelsonenzo/tmux-appimage#14]
3.2 and 3.2a were released a bit ago. Wondering if there will be an appimage for them built.

**Comment by jrwrigh** [comment]
You might be able to automate the process easily using GH Actions: https://dev.to/tyu1996/automate-stuffs-with-github-actions-on-publishing-appimage-4pl1

https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html

**Comment by menash134** [comment]
Hi Nelsonenzo, Could you please release appimage for the new tmux? As Jrwrigh said, it is supereasy to put as github action. Thanks for your wonderful contribution. Hope to get a reply soon!! Thanks

**Comment by zealouskestrel** [comment]
hey @menash134 you can clone the git and build your self for specific version with change the RELEASE_TAG to what version you want in DockerFile.
ex.
RELEASE_TAG=3.2a 
i've just build it and it's amazing have new feature

**Comment by nelsonenzo** [comment]
@menash134 @zealousKestrel @jrwrigh I apologize for my delinquency here, check out the latest release fresh off the printing press https://github.com/nelsonenzo/tmux-appimage/releases/tag/3.2a

**Comment by kiyoon** [comment]
Thanks for the idea, @jrwrigh 

I just made a fork of this repository and added a github action to automatically build and release the latest tmux as soon as it gets updated.

https://github.com/kiyoon/tmux-appimage
