### ISSUE TITLE
Rename the binary to tmux

### ISSUE THREAD

**Issue by Wsine** [nelsonenzo/tmux-appimage#16]
I use https://github.com/zyedidia/eget to manage the prebuilt binary. Would you consider renaming the binary to `tmux` so that the installation could be much simplified in one line `eget nelsonenzo/tmux-appimage`

**Comment by nelsonenzo** [comment]
Great idea. I named the latest release tmux.appimage and eget nelsonenzo/tmux-appimage downloaded it renamed it nicely. Thank you.
