### ISSUE TITLE
tmux 3.3a not built

### ISSUE THREAD

**Issue by btegs** [nelsonenzo/tmux-appimage#19]
Make sure if this project is abandoned or not, but the 3.3 series has been out: https://github.com/tmux/tmux/releases

**Comment by kiyoon** [comment]
Hi,
I just made a fork of this repository and added a github action to automatically build and release the latest tmux as soon as it gets updated.

https://github.com/kiyoon/tmux-appimage

**Comment by nelsonenzo** [comment]
@kiyoon Let me know if you want to take over maintenance permanently and I can deprecate this project and redirect to you.
Otherwise, I will probably do something similar for automation builds.
Thanks.
Nelson

**Comment by kiyoon** [comment]
@nelsonenzo Yes, I mainly use tmux through appimage still so I can maintain this!
