### ISSUE TITLE
zsh-spawned processes' argv[0] substituted with tmux executable path

### ISSUE THREAD

**Issue by ynco** [nelsonenzo/tmux-appimage#2]
$ ./tmux-3.0a-x86_64.AppImage -c /bin/zsh
    <enter tmux session>
    $ touch
    ./tmux-3.0a-x86_64.AppImage: missing file operand
    $ exit
    <leave tmux session>

Extracting the AppImage works around the issue:

    $ ./tmux-3.0a-x86_64.AppImage --appimage-extract
    <enter tmux session>
    $ squashfs-root/usr/bin/tmux -c /bin/zsh
    $ touch
    touch: missing file operand
    $ exit
    <leave tmux session>

Reproducible on:

  * Debian GNU/Linux 9 (stretch)
  * Ubuntu 18.04.3 LTS (Bionic Beaver)
  * CentOS release 6.4 (Final)

This issue does not arise when bash is used as login shell.

**Comment by yutkat** [comment]
Same here! ArchLinux(2020.03.08)

**Comment by nelsonenzo** [comment]
Thanks, I'll take a look.

**Comment by nelsonenzo** [comment]
this draft image should have it fixed if you want to give it a try.  https://github.com/nelsonenzo/tmux-appimage/releases/tag/untagged-aa871b406b1cc1107c2a

**Comment by yutkat** [comment]
I'm trying to test. But this link is 404.

**Comment by nelsonenzo** [comment]
sorry about that, i had failed to publish the draft. it's visible now.

**Comment by yutkat** [comment]
I checked it. It's work! Thank you :smile:

**Comment by yutkat** [comment]
When will you officially release it?
I can't wait!

**Comment by nelsonenzo** [comment]
Released. Thanks for your patience in these strange times.
