### ISSUE TITLE
open terminal failed: missing or unsuitable terminal: screen-256color

### ISSUE THREAD

**Issue by c02y** [nelsonenzo/tmux-appimage#9]
1. Empty ~/.tmux.conf
2. execute tmux-3.1b-x86_64.appimage file as binary
3. screen-256color as the TERM value set in my ~/.bashrc
4. `uname -r` = "5.7.10-1-MANJARO"
5. `bash -v` = "GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)"
6. KDE Plasma if this matters
7. Tried in Konsole and Alacritty
```
$ ./tmux-3.1b-x86_64.appimage 
open terminal failed: missing or unsuitable terminal: screen-256color

$ tmux
# works OK, tmux -v="tmux 3.1b" (/usr/bin/tmux is installed using system package manager)

````
I don't know if you can reproduce this problem, please kill all tmux process before trying it since it sometimes work OK when other tmux processes are already running

**Comment by yury** [comment]
Same if TERM is `xterm-256color`

**Comment by nelsonenzo** [comment]
The latest appimage build and release should fix this.  Sorry for such a long delay.
https://github.com/nelsonenzo/tmux-appimage/releases/tag/3.2a

**Comment by qlibp** [comment]
With `TERM=xterm`, tmux.appimage3.2a & 3.3a not work on ubuntu 20.04 docker(I use `--appimage-extract`), but apt installed one, which is 3.2a works. 

But with my local ubuntu 20.04(not a docker), tmux.appimage3.2a works.

It's the `--appimage-extract` flag that trigger this behavior. Verify on the same docker image with libfuse installed, I could run tmux.appimage as usual, but not `--appimage-extract` method
